/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Site = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const DailyReport = IDL.Record({
  'id' : IDL.Nat,
  'labourCount' : IDL.Nat,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'siteId' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'workDone' : IDL.Text,
});
export const FinancialSummary = IDL.Record({
  'balance' : IDL.Float64,
  'totalIncome' : IDL.Float64,
  'totalExpense' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'txType' : IDL.Text,
  'siteId' : IDL.Nat,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDailyReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addReportPhoto' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getDailyReportsForSite' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailyReport)],
      ['query'],
    ),
  'getFinancialSummaryForSite' : IDL.Func(
      [IDL.Nat],
      [FinancialSummary],
      ['query'],
    ),
  'getOverallFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getReportPhoto' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
  'getSite' : IDL.Func([IDL.Nat], [Site], ['query']),
  'getTransactionsForSite' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'updateSiteStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Site = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const DailyReport = IDL.Record({
    'id' : IDL.Nat,
    'labourCount' : IDL.Nat,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'siteId' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'workDone' : IDL.Text,
  });
  const FinancialSummary = IDL.Record({
    'balance' : IDL.Float64,
    'totalIncome' : IDL.Float64,
    'totalExpense' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'txType' : IDL.Text,
    'siteId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDailyReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReportPhoto' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getDailyReportsForSite' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyReport)],
        ['query'],
      ),
    'getFinancialSummaryForSite' : IDL.Func(
        [IDL.Nat],
        [FinancialSummary],
        ['query'],
      ),
    'getOverallFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getReportPhoto' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
    'getSite' : IDL.Func([IDL.Nat], [Site], ['query']),
    'getTransactionsForSite' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'updateSiteStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };