/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyReport {
  'id' : bigint,
  'labourCount' : bigint,
  'date' : string,
  'notes' : string,
  'siteId' : bigint,
  'photo' : [] | [ExternalBlob],
  'workDone' : string,
}
export type ExternalBlob = Uint8Array;
export interface FinancialSummary {
  'balance' : number,
  'totalIncome' : number,
  'totalExpense' : number,
}
export interface Site {
  'id' : bigint,
  'status' : string,
  'clientName' : string,
  'name' : string,
  'location' : string,
  'startDate' : string,
}
export interface Transaction {
  'id' : bigint,
  'date' : string,
  'notes' : string,
  'category' : string,
  'txType' : string,
  'siteId' : bigint,
  'amount' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDailyReport' : ActorMethod<
    [bigint, string, string, bigint, string],
    bigint
  >,
  'addReportPhoto' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addTransaction' : ActorMethod<
    [bigint, string, string, string, number, string],
    bigint
  >,
  'createSite' : ActorMethod<[string, string, string, string], bigint>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllSites' : ActorMethod<[], Array<Site>>,
  'getDailyReportsForSite' : ActorMethod<[bigint], Array<DailyReport>>,
  'getFinancialSummaryForSite' : ActorMethod<[bigint], FinancialSummary>,
  'getOverallFinancialSummary' : ActorMethod<[], FinancialSummary>,
  'getReportPhoto' : ActorMethod<[bigint], ExternalBlob>,
  'getSite' : ActorMethod<[bigint], Site>,
  'getTransactionsForSite' : ActorMethod<[bigint], Array<Transaction>>,
  'updateSiteStatus' : ActorMethod<[bigint, string], undefined>,
  'updateTransaction' : ActorMethod<
    [bigint, string, string, string, number, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];